plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/a723088/dev/jsloyer/public"
publishOrigin = "config"
commandOrigin = "config"
command = "hugo --gc --minify"

[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.147.1"
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]