baseurl = "http://www.jeffsloyer.io/"
languageCode = "en-us"
title = "JeffSloyer.io"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
copyright = "Code released under the Apache 2.0 license."

disqusShortname = "jeffsloyerio"
googleAnalytics = "UA-404795-24"

[author]
  name = "Jeff Sloyer"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Thoughts on Tech and other interests..."
  Author = "Jeff Sloyer"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/jsloyer"
[[params.social]]
  title = "github"
  url = "https://github.com/jsloyer"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -180
[[menu.main]]
  name = "Speaking"
  url = "/speaking/"
  weight = -160
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -140
